### ISSUE TITLE
Remove duplication in typing backports?

### ISSUE THREAD

**Issue by emmatyping** [jaraco/backports.typing#3]
Hello,

I am a collaborator on [mypy](https://github.com/python/mypy). We recently came across someone who was using this package with mypy, and it was causing issues. The problem was trying to use `backports.typing.{type}` as a valid type. Since there is already the `typing` module and backport, I was interested in the possibility of removing this package from PyPI, and pointing to the official backport when the user tries to install it. That way confusion is avoided and everyone can use the official typing. You can see the context and the issue [here](https://github.com/python/mypy/issues/1153#issuecomment-336296809). Thanks!

Ethan

**Comment by jaraco** [comment]
It's kinda strange that typing exists. It masks a stdlib module, so if you install it on Python 3, you still get the stdlib version when `import typing`.

But if that's the recommended way to provide cross-version compatibility, then there's no need for backports. So be it.

**Comment by jaraco** [comment]
I've removed it from PyPI.

**Comment by enkidulan** [comment]
@jaraco removing `backports.typing` from pypi have broken my builds. You could release a new version with a deprecation warning and deprecate this package without removing it from pypi.

**Comment by emmatyping** [comment]
@enkidulan, you should just move to using `typing`. The typing module has everything you need.

**Comment by enkidulan** [comment]
@ethanhs I'm using `typing` at the current project and will use it for future projects as well. But try to think about removing distribution from `pypi` in context of supporting legacy code or projects that are not in active development state. There are some [number of packages that have `backports.typing` as dependency]( https://github.com/search?utf8=%E2%9C%93&q=%22backports.typing%22&type=Code) and recently they all become impossible to install... Probably most ppl will resolve this issue by creating an internal release of `backports.typing` instead of migrating all to `typing`, especially in case of using 3rd party libraries that are dependent on `backports.typing`.

I don't really see why removing `backports.typing` from pypi was necessary...

**Comment by jaraco** [comment]
Since [gvr requested it be removed](https://github.com/python/mypy/issues/1153#issuecomment-336296809), I found it difficult to argue.

I presume by now the damage is done, but if you wish to re-publish backports.typing (perhaps with the deprecation warning), feel free to register and upload the dists. If you would like me to hand over this repo to your account, I'm happy to do that too.

**Comment by enkidulan** [comment]
That is scary :) 

I'm willing to contribute to making deprecation procedure of `backports.typing` less painful if there will be any demand for it. So far it seems that no one cares...
